name: Build docs and check cloudformation and dead links

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    name: build docs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository 
      uses: actions/checkout@v3.0.0
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Build documentation
      run: |
        mkdocs build
    - name: Setup cloudformation linter 
      uses: ScottBrenner/cfn-lint-action@v2.2.1
    - name: Run cloudformation lint 
      run: cfn-lint -t stack.yml
    - name: Setup markdown link check 
      run: |
        echo -e "{\"ignorePatterns\": [{\"pattern\": \".*(localhost|127.0.0.1).*\"}], \"aliveStatusCodes\": [403, 429, 200]}" >> markdown-link-check-config.yaml   # To exclude links(localhost, 127.0.0.1) and status code(403, 429) irrelevant to the inspection 
    - name: Check dead links 
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        folder-path: '.'
        config-file: 'markdown-link-check-config.yaml'
        use-verbose-mode: 'yes'
        use-quiet-mode: 'yes'
