name: Build docs and check cloudformation and dead links

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-check:
    name: build docs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository 
      uses: actions/checkout@v3.0.0
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install mkdocs-linkcheck
    - name: Build documentation
      run: |
        mkdocs build
    - name: Setup cloudformation linter 
      uses: ScottBrenner/cfn-lint-action@v2.2.1
    - name: Run cloudformation lint 
      run: cfn-lint -t stack.yml
    - name: Setup markdown link check 
      run: |
        npm install -g markdown-link-check@3
    - name: Check dead links 
      run: find . -name \*.md -print0 | xargs -0 -n1 markdown-link-check